### ISSUE TITLE
Use the LatLong package

### ISSUE THREAD

**Issue by synw** [NiKoTron/geohex#2]
Could it be possible to use the [LatLong](https://pub.dev/packages/latlong) package for storing coordinates? It is pretty much standard and used in many packages. It would be useful to support it to avoid type conversions when working with other libs

This would avoid having to check coordinates validity in `byLocation` because `LatLng` does it

**Comment by NiKoTron** [comment]
I wanted to use it, but unfortunately, [LatLong](https://github.com/MikeMitterer/dart-latlong) package marked as archived and deprecated by the original author. and it will not be supported anymore :(((

**Comment by synw** [comment]
Wow I did not see that! Some widely used packages like Flutter map depend on it. We definitely need a replacement. I have [geopoint](https://github.com/synw/geopoint) that handles geospatial data structures but it does not do coordinates verification, maybe I should add it and stop using LatLong
